# Generated by Django 2.0.2 on 2019-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiarcuser',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='major',
            field=models.CharField(choices=[('01', '컴퓨터공학과'), ('02', '산업공학과'), ('03', '전기전자공학부'), ('04', '법학부'), ('05', '자율전공학부'), ('99', '없음')], default='01', max_length=2, verbose_name='major'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='minor',
            field=models.CharField(choices=[('01', '컴퓨터공학과'), ('02', '산업공학과'), ('03', '전기전자공학부'), ('04', '법학부'), ('05', '자율전공학부'), ('99', '없음')], default='99', max_length=2, verbose_name='minor'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='semester',
            field=models.CharField(choices=[('0', '신입생'), ('1', '1학년 1학기'), ('2', '1학년 2학기'), ('3', '2학년 1학기'), ('4', '2학년 2학기'), ('5', '3학년 1학기'), ('6', '3학년 2학기'), ('7', '4학년 1학기'), ('8', '4학년 2학기'), ('9', '초과학기')], default='1', max_length=1, verbose_name='semester'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='student_id',
            field=models.CharField(default='B000000', max_length=8, verbose_name='student_id'),
        ),
        migrations.AlterField(
            model_name='hiarcuser',
            name='status',
            field=models.CharField(choices=[('1', '재학생'), ('2', '군휴학'), ('3', '휴학생'), ('4', '졸업생')], default='1', max_length=1, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='hiarcuser',
            index=models.Index(fields=['student_id'], name='hiarc_user_student_1f5dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='hiarcuser',
            index=models.Index(fields=['email'], name='hiarc_user_email_24ce42_idx'),
        ),
        migrations.AddIndex(
            model_name='hiarcuser',
            index=models.Index(fields=['username'], name='hiarc_user_usernam_5fc41f_idx'),
        ),
    ]
